site_name: Baza wiedzy CTF
site_description: 'Pomocna baza wiedzy na CTFy'
site_author: 'Arek Arqsz Maruszczak'

# Repo
repo_name: 'TheArqsz/ctf-wiki'
repo_url: 'https://github.com/TheArqsz/ctf-wiki'

# Copyright
copyright: "Copyright &copy; 2020 Arek 'Arqsz' Maruszczak"

theme:
    name: 'material'
    favicon: 'assets/images/favicon.ico'
    palette:
        primary: 'green'
        accent: 'green'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'    
    logo:
        icon: 'bug_report'
    language: 'pl'
    feature:
        tabs: true
extra:
    search:
        language: 'pl'
    social:
        - type: 'github'
          link: 'https://github.com/TheArqsz'
        - type: 'twitter'
          link: 'https://twitter.com/Arqsz'
        - type: 'telegram'
          link: 'https://telegram.me/Arqsz'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/amaruszczak'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
        linenums: true
    - toc:
        permalink: true

# Plugins
plugins:
    - search
    - minify:
        minify_html: true
    