site_name: Baza wiedzy CTF
site_description: 'Pomocna baza wiedzy na CTFy'
site_author: 'Arek Arqsz Maruszczak'

# Repo
repo_name: 'TheArqsz/ctf-wiki'
repo_url: 'https://github.com/TheArqsz/ctf-wiki'

# Copyright
copyright: "Copyright &copy; 2020 Arek 'Arqsz' Maruszczak"

theme:
    name: 'material'
    favicon: 'assets/images/favicon.ico'
    palette:
        primary: 'green'
        accent: 'green'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'    
    logo:
        icon: 'bug_report'
    language: 'pl'
    feature:
        tabs: true

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
        linenums: true
    - toc:
        permalink: true

# Plugins
plugins:
    - search:
        separator: '[\-\.]+'
    - minify:
        minify_html: true
    - markdownextradata

extra:
    search:
        language: 'pl'
    social:
        - type: 'github'
          link: 'https://github.com/TheArqsz'
        - type: 'twitter'
          link: 'https://twitter.com/Arqsz'
        - type: 'telegram'
          link: 'https://telegram.me/Arqsz'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/amaruszczak'
    data:
        repo_url: 'https://github.com/TheArqsz/ctf-wiki'
        site_url: '/ctf-wiki'
    
# Remove 'Edit on Github' button
edit_uri: ''

nav:
    - Start:
        - Wstęp: index.md 
        - O CTFach: main/about.md
        - Jak zacząć?: main/how_to_start.md
        - Co dalej?: main/what_next.md

    - Web:
        - O kategorii: web/about.md
        - SQLi: web/sqlinjection.md
    - Misc:
        - Miscellaneous Introduction: misc/introduction-zh.md
        - Information Gathering Technology: misc/recon-zh.md
        - Code Analysis:
            - Commonly Used Coding in the Communication Field: misc/encode/communication-zh.md
            - Computer Related Coding: misc/encode/computer-zh.md
            - Commonly Used Encodings in the Real World: misc/encode/modern-zh.md
        - Forensic Steganography: misc/prefix-zh.md